// .dev/floor/capability-catalog-core.test.mjs — hermetic tests for the shared catalog core.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { enumerateCapabilities, renderPage, renderIndex, buildCatalog, listCommittedPages, OUT_DIR } from "./capability-catalog-core.mjs";

function makeRepo() {
  return mkdtempSync(join(tmpdir(), "pharn-cat-core-"));
}

// Write a capability at <root>/<dirRel>/<base>.md with the given frontmatter map + body.
function cap(root, dirRel, base, fm, body) {
  const dir = join(root, dirRel);
  mkdirSync(dir, { recursive: true });
  const fmLines = Object.entries(fm).map(([k, v]) => `${k}: ${Array.isArray(v) ? `[${v.map((x) => `"${x}"`).join(", ")}]` : v}`);
  writeFileSync(join(dir, `${base}.md`), `---\n${fmLines.join("\n")}\n---\n\n${body}\n`);
}

test("enumerate: role-order then slug, excludes non-role + excluded segments, no readdir dependence", () => {
  const root = makeRepo();
  try {
    // Created in non-sorted order on purpose; enumerate must still return the fixed sorted order.
    cap(
      root,
      "pharn/pharn-review/zzz",
      "zzz",
      { name: "zzz", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# zzz — flags zzz"
    );
    cap(
      root,
      "pharn/pharn-review/aaa",
      "aaa",
      { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# aaa — flags aaa"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/gg",
      "gg",
      { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# gg — asks gg"
    );
    cap(
      root,
      "pharn/pharn-core/skl",
      "skl",
      { name: "skl", role: "skill", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# skl — does skl"
    );
    // Ignored: no-role md, an eval fixture, an excluded-segment md, a docs page.
    writeFileSync(join(root, "pharn/pharn-review/aaa", "notes.md"), "# not a capability\n");
    mkdirSync(join(root, ".dev/floor"), { recursive: true });
    writeFileSync(join(root, ".dev/floor/x.md"), "---\nrole: lens\n---\n# x — excluded\n");
    mkdirSync(join(root, "docs/capabilities"), { recursive: true });
    writeFileSync(join(root, "docs/capabilities/aaa.md"), "generated page — must not be re-ingested\n");

    const caps = enumerateCapabilities(root);
    assert.deepEqual(
      caps.map((c) => c.slug),
      ["gg", "aaa", "zzz", "skl"]
    );
    assert.deepEqual(
      caps.map((c) => c.role),
      ["griller", "lens", "lens", "skill"]
    );
    assert.equal(caps[1].tagline, "flags aaa"); // em-dash prefix stripped
    assert.equal(caps[1].srcRel, "pharn/pharn-review/aaa/aaa.md");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("renderPage: full fields, GENERATED header names source, source link + install note", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/injection",
      "injection",
      {
        name: "injection",
        role: "lens",
        kind: "pharn-owned",
        version: "0.1.0",
        applies: ["universal"],
        coupling: "agnostic",
        enforces: ["P2"],
        model_tier: "sonnet",
      },
      "# injection — read untrusted CODE, flag concat into a sink"
    );
    const [c] = enumerateCapabilities(root);
    const page = renderPage(c);
    assert.match(page, /^<!-- GENERATED by \.dev\/floor\/gen-capability-catalog\.mjs from pharn\/pharn-review\/injection\/injection\.md /);
    assert.match(page, /# injection\n/);
    assert.match(page, /\| Role \| lens \|/);
    assert.match(page, /\| Coupling \| agnostic \|/);
    assert.match(page, /\| Enforces \| P2 \|/);
    assert.match(page, /## What it flags\n\nread untrusted CODE, flag concat into a sink\n/);
    assert.match(page, /\[`pharn\/pharn-review\/injection\/injection\.md`\]\(\.\.\/\.\.\/pharn\/pharn-review\/injection\/injection\.md\)/);
    assert.match(page, /No install command yet/);
    // A generated page must NOT open with a `---` role frontmatter block (else validate.mjs misclassifies it).
    assert.ok(!page.startsWith("---"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("renderPage: sparse frontmatter + missing H1 render em-dashes and the no-summary note", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-core/skl",
      "skl",
      { role: "skill", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "no heading here"
    );
    const [c] = enumerateCapabilities(root);
    const page = renderPage(c);
    assert.match(page, /# skl\n/); // name falls back to slug
    assert.match(page, /\| Coupling \| — \|/);
    assert.match(page, /\| Enforces \| — \|/);
    assert.match(page, /\| Model tier \| — \|/);
    assert.match(page, /## What it does\n\n_\(no summary line in source\)_\n/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("renderIndex: grouped by role with counts, sorted lines, empty groups skipped", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/bbb",
      "bbb",
      { name: "bbb", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# bbb — flags bbb"
    );
    cap(
      root,
      "pharn/pharn-review/aaa",
      "aaa",
      { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# aaa — flags aaa"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/gg",
      "gg",
      { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# gg — asks gg"
    );
    const idx = renderIndex(enumerateCapabilities(root));
    assert.match(idx, /^<!-- GENERATED by/);
    assert.match(idx, /# Capability catalog\n/);
    assert.match(idx, /3 capabilities, generated/);
    assert.match(idx, /## Grillers \(1\)\n\n- \[gg\]\(gg\.md\) — asks gg\n/);
    assert.match(idx, /## Lenses \(2\)\n\n- \[aaa\]\(aaa\.md\) — flags aaa\n- \[bbb\]\(bbb\.md\) — flags bbb\n/);
    assert.ok(!/## Skills/.test(idx)); // empty group skipped
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("buildCatalog is idempotent (byte-identical on a second run) and includes README + one page each", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/aaa",
      "aaa",
      { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# aaa — flags aaa"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/gg",
      "gg",
      { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# gg — asks gg"
    );
    const a = buildCatalog(root);
    const b = buildCatalog(root);
    assert.deepEqual([...a.files.entries()], [...b.files.entries()]);
    assert.deepEqual([...a.files.keys()].sort(), [`${OUT_DIR}/README.md`, `${OUT_DIR}/aaa.md`, `${OUT_DIR}/gg.md`]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("enumerate throws on a duplicate page slug (fail-closed, P5)", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/dup",
      "dup",
      { name: "one", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# one — a"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/dup",
      "dup",
      { name: "two", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# two — b"
    );
    assert.throws(() => enumerateCapabilities(root), /duplicate page slug "dup"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("listCommittedPages: absent OUT_DIR yields empty list", () => {
  const root = makeRepo();
  try {
    assert.deepEqual(listCommittedPages(root), []);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
