// .dev/floor/check-capability-catalog.test.mjs — hermetic tests for the drift checker + the CLIs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, appendFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { checkCatalog, checkReadmeCurrentState } from "./check-capability-catalog.mjs";
import { generate } from "./gen-capability-catalog.mjs";
import { OUT_DIR, README_PATH } from "./capability-catalog-core.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const MARK_BEGIN =
  "<!-- CURRENT-STATE:BEGIN — GENERATED by .dev/floor/gen-capability-catalog.mjs. DO NOT EDIT BETWEEN MARKERS. Regenerate: npm run docs:generate -->";
const MARK_END = "<!-- CURRENT-STATE:END -->";

function makeRepo() {
  return mkdtempSync(join(tmpdir(), "pharn-cat-check-"));
}
function cap(root, dirRel, base, fm, body) {
  const dir = join(root, dirRel);
  mkdirSync(dir, { recursive: true });
  const fmLines = Object.entries(fm).map(([k, v]) => `${k}: ${Array.isArray(v) ? `[${v.map((x) => `"${x}"`).join(", ")}]` : v}`);
  writeFileSync(join(dir, `${base}.md`), `---\n${fmLines.join("\n")}\n---\n\n${body}\n`);
}
// The checker now covers TWO artifacts, so the fixture repo must carry the surface the README block
// enumerates as well as the capabilities the catalog enumerates.
function seed(root, { readme = `# Fixture\n\nIntro.\n\n${MARK_BEGIN}\n\n${MARK_END}\n\nTail.\n` } = {}) {
  cap(
    root,
    "pharn/pharn-review/aaa",
    "aaa",
    { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
    "# aaa — flags aaa"
  );
  cap(
    root,
    "pharn/pharn-pipeline/grillers/gg",
    "gg",
    { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
    "# gg — asks gg"
  );
  const put = (rel, names, body) => {
    mkdirSync(join(root, rel), { recursive: true });
    for (const n of names) writeFileSync(join(root, rel, n), body);
  };
  put("pharn/pharn-contracts", ["finding-shape.md"], "# a contract\n");
  put(".claude/commands", ["pharn-spec.md", "pharn-dev-plan.md"], "# a command\n");
  put(".claude/hooks", ["protect-trusted-paths.cjs"], "// a hook\n");
  put("pharn/floor", ["validate.mjs", "validate.test.mjs"], "// a checker\n");
  if (readme !== null) writeFileSync(join(root, README_PATH), readme);
}

test("clean: after generate, checkCatalog is GREEN (ok, no findings)", () => {
  const root = makeRepo();
  try {
    seed(root);
    const { written } = generate(root);
    assert.equal(written, 3); // README + 2 pages
    const { ok, findings } = checkCatalog(root);
    assert.equal(ok, true);
    assert.deepEqual(findings, []);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("drift: mutating a committed page → RED with a DRIFT finding", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    appendFileSync(join(root, OUT_DIR, "aaa.md"), "tampered\n");
    const { ok, findings } = checkCatalog(root);
    assert.equal(ok, false);
    assert.ok(findings.some((f) => f.type === "DRIFT" && f.file === `${OUT_DIR}/aaa.md`));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("missing: adding a capability without regenerating → RED MISSING", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    cap(
      root,
      "pharn/pharn-review/ccc",
      "ccc",
      { name: "ccc", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# ccc — flags ccc"
    );
    const { ok, findings } = checkCatalog(root);
    assert.equal(ok, false);
    assert.ok(findings.some((f) => f.type === "MISSING" && f.file === `${OUT_DIR}/ccc.md`));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("orphan: a committed page with no backing capability → RED ORPHAN", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    writeFileSync(join(root, OUT_DIR, "orphan.md"), "leftover\n");
    const { ok, findings } = checkCatalog(root);
    assert.equal(ok, false);
    assert.ok(findings.some((f) => f.type === "ORPHAN" && f.file === `${OUT_DIR}/orphan.md`));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generate removes a stale page when its capability disappears", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    rmSync(join(root, "pharn/pharn-review/aaa"), { recursive: true, force: true });
    const { removed } = generate(root);
    assert.equal(removed, 1);
    const { ok } = checkCatalog(root);
    assert.equal(ok, true);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("duplicate slug surfaces as a deterministic ENUM_ERROR (not a crash)", () => {
  const root = makeRepo();
  try {
    cap(
      root,
      "pharn/pharn-review/dup",
      "dup",
      { name: "one", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# one — a"
    );
    cap(
      root,
      "pharn/pharn-pipeline/grillers/dup",
      "dup",
      { name: "two", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# two — b"
    );
    const { ok, findings } = checkCatalog(root);
    assert.equal(ok, false);
    assert.equal(findings[0].type, "ENUM_ERROR");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI: gen exits 0; check exits 0 clean, 1 on drift with the FIX line; 1 on bad target", () => {
  const root = makeRepo();
  try {
    seed(root);
    const gen = spawnSync("node", [join(HERE, "gen-capability-catalog.mjs"), root], { encoding: "utf8" });
    assert.equal(gen.status, 0);
    assert.match(gen.stdout, /wrote 3 file/);

    const clean = spawnSync("node", [join(HERE, "check-capability-catalog.mjs"), root], { encoding: "utf8" });
    assert.equal(clean.status, 0);
    assert.match(clean.stdout, /CATALOG: GREEN/);

    appendFileSync(join(root, OUT_DIR, "gg.md"), "x\n");
    const dirty = spawnSync("node", [join(HERE, "check-capability-catalog.mjs"), root], { encoding: "utf8" });
    assert.equal(dirty.status, 1);
    assert.match(dirty.stdout, /CATALOG: RED/);
    assert.match(dirty.stdout, /npm run docs:generate/);

    const bad = spawnSync("node", [join(HERE, "check-capability-catalog.mjs"), join(root, "nope")], { encoding: "utf8" });
    assert.equal(bad.status, 1);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// ================================================================================================
// Artifact 2 — the README `## Current state` block.
// ================================================================================================

test("README: GREEN right after generate, and the block is what carries the verdict", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    assert.deepEqual(checkReadmeCurrentState(root), []);
    assert.equal(checkCatalog(root).ok, true);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("README drift: editing between the markers → RED README_DRIFT", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    const text = readFileSync(join(root, README_PATH), "utf8");
    writeFileSync(join(root, README_PATH), text.replace("Capabilities — 2 built", "Capabilities — 99 built"));
    const { ok, findings } = checkCatalog(root);
    assert.equal(ok, false);
    assert.ok(findings.some((f) => f.type === "README_DRIFT" && f.file === README_PATH));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("README drift: adding a capability without regenerating → RED (the stale-count case this exists for)", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    cap(
      root,
      "pharn/pharn-review/ccc",
      "ccc",
      { name: "ccc", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# ccc — flags ccc"
    );
    assert.ok(checkReadmeCurrentState(root).some((f) => f.type === "README_DRIFT"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("README drift: hand-editing a MARKER line is itself drift (markers are inside the guarded region)", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    const text = readFileSync(join(root, README_PATH), "utf8");
    writeFileSync(join(root, README_PATH), text.replace("DO NOT EDIT BETWEEN MARKERS.", "edit freely."));
    assert.ok(checkReadmeCurrentState(root).some((f) => f.type === "README_DRIFT"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("README markers: missing, duplicated, and inverted each → RED README_MARKERS naming the defect", () => {
  const cases = [
    ["# F\n\nno markers\n", /no <!-- CURRENT-STATE:BEGIN/],
    [`# F\n\n${MARK_BEGIN}\n\nbody\n`, /no <!-- CURRENT-STATE:END/],
    [`# F\n\n${MARK_BEGIN}\n${MARK_END}\n\n${MARK_BEGIN}\n${MARK_END}\n`, /2 BEGIN markers found/],
    [`# F\n\n${MARK_END}\n\n${MARK_BEGIN}\n`, /inverted/],
  ];
  for (const [readme, expected] of cases) {
    const root = makeRepo();
    try {
      seed(root, { readme });
      const findings = checkReadmeCurrentState(root);
      assert.equal(findings.length, 1);
      assert.equal(findings[0].type, "README_MARKERS");
      assert.match(findings[0].problem, expected);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }
});

test("README missing entirely → RED README_MISSING (fail-closed, never a silent GREEN)", () => {
  const root = makeRepo();
  try {
    seed(root, { readme: null });
    const findings = checkReadmeCurrentState(root);
    assert.deepEqual(
      findings.map((f) => f.type),
      ["README_MISSING"]
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("README: an enumeration failure surfaces as ENUM_ERROR, not a crash and not a pass", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    rmSync(join(root, ".claude/hooks"), { recursive: true, force: true });
    const findings = checkReadmeCurrentState(root);
    assert.equal(findings.length, 1);
    assert.equal(findings[0].type, "ENUM_ERROR");
    assert.match(findings[0].problem, /expected directory is missing or unreadable/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI: README drift alone is enough to exit 1, with the fix command printed", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    const text = readFileSync(join(root, README_PATH), "utf8");
    writeFileSync(join(root, README_PATH), text.replace("Contracts — 1", "Contracts — 7"));

    const run = spawnSync("node", [join(HERE, "check-capability-catalog.mjs"), root], { encoding: "utf8" });
    assert.equal(run.status, 1);
    assert.match(run.stdout, /CATALOG: RED/);
    assert.match(run.stdout, /README_DRIFT/);
    assert.match(run.stdout, /npm run docs:generate/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
