// .dev/floor/gen-capability-catalog.test.mjs — hermetic tests for the generator.
//
// The generator is ADVISORY (running it is orchestration, not a guarantee — P0); what these tests pin
// is that it produces exactly the bytes the checker demands, converges in one pass, and FAILS CLOSED
// rather than inventing or relocating a marker.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { generate } from "./gen-capability-catalog.mjs";
import { OUT_DIR, README_PATH, extractCurrentState, renderReadmeCurrentState } from "./capability-catalog-core.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const MARK_BEGIN =
  "<!-- CURRENT-STATE:BEGIN — GENERATED by .dev/floor/gen-capability-catalog.mjs. DO NOT EDIT BETWEEN MARKERS. Regenerate: npm run docs:generate -->";
const MARK_END = "<!-- CURRENT-STATE:END -->";

function makeRepo() {
  return mkdtempSync(join(tmpdir(), "pharn-cat-gen-"));
}

function cap(root, dirRel, base, fm, body) {
  const dir = join(root, dirRel);
  mkdirSync(dir, { recursive: true });
  const fmLines = Object.entries(fm).map(([k, v]) => `${k}: ${Array.isArray(v) ? `[${v.map((x) => `"${x}"`).join(", ")}]` : v}`);
  writeFileSync(join(dir, `${base}.md`), `---\n${fmLines.join("\n")}\n---\n\n${body}\n`);
}

/** A minimal but complete repo: two capabilities + the four enumerated dirs + a marked README. */
function seed(root, { readme = `# Fixture\n\nIntro.\n\n${MARK_BEGIN}\n\n${MARK_END}\n\nTail.\n` } = {}) {
  cap(
    root,
    "pharn/pharn-review/aaa",
    "aaa",
    { name: "aaa", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
    "# aaa — flags aaa"
  );
  cap(
    root,
    "pharn/pharn-pipeline/grillers/gg",
    "gg",
    { name: "gg", role: "griller", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
    "# gg — asks gg"
  );
  const put = (rel, names, body) => {
    mkdirSync(join(root, rel), { recursive: true });
    for (const n of names) writeFileSync(join(root, rel, n), body);
  };
  put("pharn/pharn-contracts", ["finding-shape.md"], "# a contract\n");
  put(".claude/commands", ["pharn-spec.md", "pharn-dev-plan.md"], "# a command\n");
  put(".claude/hooks", ["protect-trusted-paths.cjs"], "// a hook\n");
  put("pharn/floor", ["validate.mjs", "validate.test.mjs"], "// a checker\n");
  if (readme !== null) writeFileSync(join(root, README_PATH), readme);
}

test("generate: writes the catalog AND splices the README block between the existing markers", () => {
  const root = makeRepo();
  try {
    seed(root);
    const { written, removed, readmeUpdated } = generate(root);
    assert.equal(written, 3); // catalog README index + one page per capability
    assert.equal(removed, 0);
    assert.equal(readmeUpdated, true);

    const text = readFileSync(join(root, README_PATH), "utf8");
    assert.equal(extractCurrentState(text).region, renderReadmeCurrentState(root));
    assert.match(text, /^# Fixture\n\nIntro\.\n\n<!-- CURRENT-STATE:BEGIN/); // hand prose untouched
    assert.match(text, /CURRENT-STATE:END -->\n\nTail\.\n$/);
    assert.match(text, /\*\*Capabilities — 2 built\*\*/);
    assert.ok(existsSync(join(root, OUT_DIR, "aaa.md")));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generate: a second run is a true no-op — identical bytes and no README write", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    const after1 = readFileSync(join(root, README_PATH), "utf8");
    const page1 = readFileSync(join(root, OUT_DIR, "aaa.md"), "utf8");

    const second = generate(root);
    assert.equal(second.readmeUpdated, false, "nothing changed, so the README must not be rewritten");
    assert.equal(readFileSync(join(root, README_PATH), "utf8"), after1);
    assert.equal(readFileSync(join(root, OUT_DIR, "aaa.md"), "utf8"), page1);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generate: re-splices after a capability is added (the drift the checker would have caught)", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    cap(
      root,
      "pharn/pharn-review/bbb",
      "bbb",
      { name: "bbb", role: "lens", kind: "pharn-owned", version: "0.1.0", applies: ["universal"] },
      "# bbb — flags bbb"
    );
    const { readmeUpdated } = generate(root);
    assert.equal(readmeUpdated, true);
    assert.match(readFileSync(join(root, README_PATH), "utf8"), /\*\*Capabilities — 3 built\*\*/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generate: deletes a stale catalog page when its capability disappears", () => {
  const root = makeRepo();
  try {
    seed(root);
    generate(root);
    rmSync(join(root, "pharn/pharn-review/aaa"), { recursive: true, force: true });
    const { removed } = generate(root);
    assert.equal(removed, 1);
    assert.equal(existsSync(join(root, OUT_DIR, "aaa.md")), false);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generate: fails closed on a missing README, and on missing / duplicated markers", () => {
  const noReadme = makeRepo();
  try {
    seed(noReadme, { readme: null });
    assert.throws(() => generate(noReadme), /ENOENT/);
  } finally {
    rmSync(noReadme, { recursive: true, force: true });
  }

  const noMarkers = makeRepo();
  try {
    seed(noMarkers, { readme: "# Fixture\n\nNo markers at all.\n" });
    assert.throws(() => generate(noMarkers), /no <!-- CURRENT-STATE:BEGIN/);
    // The generator must NOT have invented a marker pair to write into.
    assert.equal(readFileSync(join(noMarkers, README_PATH), "utf8"), "# Fixture\n\nNo markers at all.\n");
  } finally {
    rmSync(noMarkers, { recursive: true, force: true });
  }

  const dupe = makeRepo();
  try {
    seed(dupe, { readme: `# F\n\n${MARK_BEGIN}\n\n${MARK_END}\n\n${MARK_BEGIN}\n\n${MARK_END}\n` });
    assert.throws(() => generate(dupe), /2 BEGIN markers found/);
  } finally {
    rmSync(dupe, { recursive: true, force: true });
  }
});

test("CLI: exits 0 and reports the README block state on each run", () => {
  const root = makeRepo();
  try {
    seed(root);
    const first = spawnSync("node", [join(HERE, "gen-capability-catalog.mjs"), root], { encoding: "utf8" });
    assert.equal(first.status, 0);
    assert.match(first.stdout, /wrote 3 file\(s\) under docs\/capabilities\/; README\.md current-state block updated/);

    const second = spawnSync("node", [join(HERE, "gen-capability-catalog.mjs"), root], { encoding: "utf8" });
    assert.equal(second.status, 0);
    assert.match(second.stdout, /README\.md current-state block already current/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("CLI: a marker defect is a non-zero exit, not a silent success", () => {
  const root = makeRepo();
  try {
    seed(root, { readme: "# Fixture\n\nNo markers.\n" });
    const run = spawnSync("node", [join(HERE, "gen-capability-catalog.mjs"), root], { encoding: "utf8" });
    assert.notEqual(run.status, 0);
    assert.match(run.stderr, /no <!-- CURRENT-STATE:BEGIN/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
